### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by cassianotadaoyasumitsu** [cassianotadaoyasumitsu/posto_ipiranga#2]
cannot use &(ufoRepository literal) (value of type *ufoRepository) as ufo.Repository value in return statement: *ufoRepository does not implement ufo.Repository (missing method List)

````
func NewUfoRepository(db *sqlx.DB) ufo.Repository {
	return &ufoRepository{db: db}
}
```

```
func NewUfoRepository() ufo.Repository {
	return &ufoRepository{
		store: make(map[string]*ufo.Ufo),
	}
}
```

**Comment by rhty** [comment]
I think you've implemented `ufo.Repository` as an interface that has some methods. And here, your `*ufoRepository` doesn't have those methods. That's what "*ufoRepository does not implement ufo.Repository (missing method List)" means.

**Comment by cassianotadaoyasumitsu** [comment]
@rhty 
It's the 'List' method I have, but I have no idea where to do it or to put it.  😭 
I remember you told me something like this before. I'll double check what can I be missing.

**Comment by fltd** [comment]
Thanks @rhty!

@cassianotadaoyasumitsu you need a method called `List` implemented under `ufoRepository`.
Something like this

```go
func (u *ufoRepository) List(...) {
    ...
}
```

Please see if it works :wink:

**Comment by cassianotadaoyasumitsu** [comment]
@fltd @rhty Thanks, I did the methods, and looks fine for now. I'll keep developing. 
Keep you informed about how it's going.
